### ISSUE TITLE
how to build this?

### ISSUE THREAD

**Issue by Micha-Btz** [XanMead/stern-halma#1]
Hey, 

can you please describe how to get this game running?

thanks Micha

**Comment by XanMead** [comment]
Hi Micha,

Sorry, I abandoned that project I while back. It's not complete. I'll
likely get back to it once the semester's over.

**Comment by Micha-Btz** [comment]
sad to hear. for the moment there is no actual game for this the most games are more then ten years old and so most of the depends can not more be solved.

please telle me if you go by .
